modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="moore"
version="1.0.0"
displayName="Mo'ore"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="heitz, MCreator"

[[dependencies.moore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




